### ISSUE TITLE
Broke with core-2022.3.1

### ISSUE THREAD

**Issue by jscmidt** [chaptergy/lightalarm-card#16]
Since this update (but I skipped some other updates) the input_select field isn’t displayed correctly:
![871E3429-75E4-4706-8D1A-16A4A9ED42A2](https://user-images.githubusercontent.com/74502558/157044843-5b7e6042-4e5c-48d8-92a5-e576edcbe260.jpeg)

**Comment by albizrik** [comment]
+1 got the same problem

**Comment by 8pu5** [comment]
+1 same problem

**Comment by chaptergy** [comment]
Yeah, I noticed when I updated my HA as well a few days ago. However I wasn't able to find a quick fix yet, as I do not have much spare time right now, and the documentation of home assistant is lacking on the topic of custom cards using the existing components. 

The problem is the `paper` elements having been removed from home assistant, now only material web components should be used. However just replacing it with a material web component does not work. Unfortunately you'll have to wait until I have more time to research this, or if someone knows how to work with the new `mwc` elements, PRs let me know.

Also please refrain from the `+1` comments, use the reaction emojis instead.

**Comment by Ortep** [comment]
Here the same problem. The selector also does not work. I cannot change te setting

**Comment by annaoskarson** [comment]
Would be nice if this could be fixed!

**Comment by subxero** [comment]
temporarily you can hide the current dropdown and use this select which works, if someone dares to change the code to use the new compatible form.
https://github.com/mattieha/select-list-card/releases/tag/v1.2.0

**Comment by chaptergy** [comment]
I _finally_ got around to fixing this in release [v3.1.0](https://github.com/chaptergy/lightalarm-card/releases/tag/v3.1.0). Apparently by now, custom cards can just use the `ha-select`, though I am pretty sure that did not work any time when I tried to fix this in the past year.
